'use client';

import { createContext, useContext, useEffect, useState, ReactNode } from 'react';

type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Словари переводов
const translations = {
  ru: {
    // Общие
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.create': 'Создать',
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успешно',
    'common.confirm': 'Подтвердить',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.next': 'Далее',
    'common.back': 'Назад',
    'common.select': 'Выбрать',
    'common.close': 'Закрыть',
    
    // Навигация
    'nav.dashboard': 'Дашборд',
    'nav.leads': 'Лиды',
    'nav.boxes': 'Боксы',
    'nav.brokers': 'Интеграции',
    'nav.users': 'Пользователи',
    'nav.settings': 'Настройки',
    
    // Настройки
    'settings.title': 'Настройки CRM',
    'settings.timezone': 'Часовой пояс',
    'settings.timezone.description': 'Выберите часовой пояс для отображения времени в CRM и работы планов доставки лидов.',
    'settings.theme': 'Цветовая схема',
    'settings.theme.description': 'Выберите цветовую схему интерфейса.',
    'settings.language': 'Язык интерфейса',
    'settings.language.description': 'Выберите язык интерфейса.',
    'settings.save': 'Сохранить настройки',
    'settings.saving': 'Сохранение...',
    'settings.saved': 'Настройки сохранены',
    'settings.delivery_time_note': 'Время доставки будет рассчитываться по этому часовому поясу',
    'settings.current_time': 'Текущее время:',
    'common.updating': 'Обновление...',
    
    // Темы
    'theme.light': 'Светлая',
    'theme.dark': 'Темная',
    'theme.auto': 'Автоматически',
    
    // Пользователи
    'users.title': 'Пользователи',
    'users.create': 'Создать пользователя',
    'users.edit': 'Редактировать пользователя',
    'users.delete': 'Удалить пользователя',
    'users.regenerate_key': 'Сгенерировать новый API ключ',
    'users.email': 'Email',
    'users.name': 'Имя',
    'users.role': 'Роль',
    'users.status': 'Статус',
    'users.active': 'Активен',
    'users.inactive': 'Неактивен',
    'users.leads_count': 'Лидов',
    'users.children_count': 'Детей',
    'users.api_key': 'API ключ',
    'users.created_at': 'Создан',
    'users.search_placeholder': 'Поиск по имени или email...',
    'users.filter_all_roles': 'Все роли',
    'users.role.affiliate': 'Аффилиат',
    'users.role.affiliate_master': 'Мастер аффилиат',
    'users.role.admin': 'Администратор',
    'users.role.superadmin': 'Суперадмин',
    'users.parent': 'Родительский пользователь',
    'users.no_parent': 'Нет родителя',
    
    // Лиды
    'leads.title': 'Лиды',
    'leads.create': 'Создать лид',
    'leads.edit': 'Редактировать лид',
    'leads.delete': 'Удалить лид',
    'leads.name': 'Имя',
    'leads.phone': 'Телефон',
    'leads.email': 'Email',
    'leads.country': 'Страна',
    'leads.affiliate': 'Аффилиат',
    'leads.box': 'Бокс',
    'leads.broker': 'Брокер',
    'leads.status': 'Статус',
    'leads.created_at': 'Создан',
    'leads.updated_at': 'Обновлен',
    'leads.actions': 'Действия',
    'leads.send_attempts': 'Попытки отправки',
    'leads.attempt': 'Попытка',
    'leads.attempt_date': 'Дата попытки',
    'leads.attempt_status': 'Статус',
    'leads.attempt_error': 'Ошибка',
    'leads.attempt_success': 'Успешно',
    'leads.attempt_failed': 'Неудачно',
    'leads.attempt_pending': 'В ожидании',
    'leads.showing': 'Показано',
    'leads.of': 'из',
    'leads.total': 'всего',
    'common.load_more': 'Загрузить еще',
    
    // Боксы
    'boxes.title': 'Боксы (планы отправки)',
    'boxes.create': 'Добавить бокс',
    'boxes.edit': 'Редактировать бокс',
    'boxes.delete': 'Удалить бокс',
    'boxes.name': 'Название',
    'boxes.description': 'Описание',
    'boxes.is_active': 'Активен',
    'boxes.brokers_count': 'Брокеров',
    'boxes.leads_count': 'Лидов',
    'boxes.description_text': 'Боксы определяют приоритетность отправки лидов на брокеров',
    'boxes.new_box': 'Новый бокс',
    'boxes.countries': 'Страны',
    'boxes.countries_placeholder': 'Выберите страны или оставьте пустым для всех',
    'boxes.countries_hint': 'Если не выбрано ни одной страны, бокс будет универсальным для всех стран',
    'boxes.brokers': 'Брокеры (приоритет 1 = самый высокий)',
    'boxes.brokers_instruction': 'Добавьте брокеров с приоритетами',
    'boxes.add_broker': '+ Добавить брокера',
    'boxes.no_boxes': 'Боксов пока нет',
    'boxes.name_placeholder': 'Например: EU Premium',
    'boxes.countries_all': 'Все страны',
    'boxes.countries_label': 'Страны:',
    'boxes.description_text': 'Боксы определяют приоритетность отправки лидов на брокеров',
    'boxes.updated_successfully': 'Бокс обновлен!',
    'boxes.created_successfully': 'Бокс создан!',
    'boxes.confirm_delete': 'Удалить бокс?',
    'boxes.select_broker': 'Выберите брокера',
    'boxes.delivery_time': 'Доставлено',
    'boxes.lead_cap': 'Капа лидов:',
    'boxes.lead_cap_unlimited': '∞',
    'boxes.lead_cap_hint': '(пусто = без лимита)',
    'boxes.from': 'от',
    'boxes.to': 'до',
    'boxes.deleted_successfully': 'Бокс удален успешно',
    'boxes.save_error': 'Ошибка сохранения бокса',
    'boxes.delete_error': 'Ошибка удаления бокса',
    'boxes.delete_confirm_title': 'Удалить бокс',
    'boxes.max_brokers_error': 'Максимум 10 брокеров в боксе',
    'boxes.edit': 'Редактировать',
    'boxes.delete': 'Удалить',
    'boxes.delivery_plan': 'План отправки:',
    'common.error': 'Ошибка',
    'common.adding': 'Добавление...',
    'common.back': 'Назад',
    'leads.all_leads': 'Все лиды',
    'brokers.update_integration': 'Обновить',
    'brokers.save_integration': 'Сохранить',
    'brokers.edit': 'Редактировать',
    'brokers.delete': 'Удалить',
    'brokers.add_parameter': '+ Добавить параметр',
    'brokers.no_integrations': 'Нет созданных интеграций',
    'brokers.unknown_template': 'Неизвестный шаблон',
    'brokers.no_active_brokers': 'Нет активных брокеров',
    'brokers.template': 'Шаблон',
    'brokers.name_example': 'Например: Trackbox NIK',
    'brokers.manual_integration': 'Ручная интеграция',
    'brokers.created_successfully': 'Интеграция создана успешно',
    'brokers.updated_successfully': 'Интеграция обновлена успешно',
    'brokers.deleted_successfully': 'Интеграция удалена успешно',
    'brokers.create_error': 'Ошибка создания интеграции',
    'brokers.update_error': 'Ошибка обновления интеграции',
    'brokers.delete_error': 'Ошибка удаления интеграции',
    'brokers.delete_confirm_title': 'Удалить интеграцию',
    'brokers.delete_confirm': 'Вы уверены, что хотите удалить эту интеграцию?',
    'brokers.manual_integration_not_implemented': 'Ручная интеграция будет реализована позже',
    
    // Интеграции
    'brokers.title': 'Интеграции',
    'brokers.create': 'Создать интеграцию',
    'brokers.edit': 'Редактировать',
    'brokers.delete': 'Удалить',
    'brokers.name': 'Название',
    'brokers.code': 'Код',
    'brokers.method': 'Метод запроса',
    'brokers.url': 'URL',
    'brokers.headers': 'Заголовки',
    'brokers.body': 'Тело запроса',
    'brokers.is_active': 'Активен',
    'brokers.method.get': 'GET',
    'brokers.method.post': 'POST',
    'brokers.method.put': 'PUT',
    'brokers.method.patch': 'PATCH',
    'brokers.method.delete': 'DELETE',
    'brokers.available_macros': 'Доступные макросы:',
    'brokers.macro.firstName': 'Имя',
    'brokers.macro.lastName': 'Фамилия',
    'brokers.macro.email': 'Email',
    'brokers.macro.phone': 'Телефон (полный)',
    'brokers.macro.phonePrefix': 'Код страны (автоопределение)',
    'brokers.macro.phoneNumber': 'Номер без кода страны',
    'brokers.macro.password': 'Пароль (автогенерация Aa12345!)',
    'brokers.macro.country': 'Страна',
    'brokers.macro.aff': 'Affiliate',
    'brokers.macro.bx': 'Box',
    'brokers.macro.funnel': 'Funnel',
    'brokers.macro.ip': 'IP адрес',
    'brokers.macro.lang': 'Язык',
    'brokers.macro.url': 'URL',
    'brokers.macro.clickid': 'Click ID',
    'brokers.name_placeholder': 'Например: Trackbox NIK',
    'brokers.url_placeholder': 'https://example.com/api/endpoint',
    'brokers.url_hint_get': 'Для GET все параметры указываются прямо в URL',
    'brokers.url_hint_post': 'URL для отправки запроса',
    'brokers.integration_parameters': 'Параметры интеграции',
    'brokers.parameters_description': 'Эти параметры можно использовать в URL, Headers и Body через макросы, например: ${partnerId}',
    'brokers.password_generation_settings': 'Настройки генерации пароля',
    'brokers.password_settings_description': 'Настройки используются при генерации макроса ${password}',
    'brokers.password_length': 'Длина пароля',
    'brokers.uppercase_letters': 'Заглавные буквы (A-Z)',
    'brokers.lowercase_letters': 'Строчные буквы (a-z)',
    'brokers.digits': 'Цифры (0-9)',
    'brokers.special_chars': 'Спецсимволы',
    'brokers.which_special_chars': 'Какие спецсимволы использовать',
    'brokers.enable_pull_api': 'Включить Pull API (получение статусов от брокера)',
    'brokers.pull_url': 'Pull URL',
    'brokers.pull_interval': 'Интервал опроса (минут)',
    'brokers.pull_interval_description': 'Как часто запрашивать обновления (5-1440 мин)',
    'brokers.pull_headers': 'Pull Headers (JSON)',
    'brokers.pull_body': 'Pull Body (JSON)',
    'brokers.pull_macros': 'Доступные макросы: ${from} и ${to} для дат',
    'brokers.pull_info': 'Pull API',
    'brokers.pull_info_description': 'Система будет автоматически запрашивать обновления статусов лидов у брокера с указанным интервалом. Полученные статусы (DEPOSITOR, FTD, и т.д.) будут обновляться в CRM автоматически.',
    
    // Лиды
    'leads.title': 'Лиды',
    'leads.search_placeholder': 'Q Search',
    'leads.filters': 'Фильтры',
    'leads.columns': 'Колонки',
    'leads.available_fields': 'Доступные поля',
    'leads.in_use': 'Используются',
    'leads.search_by_field': 'Поиск по полю...',
    'leads.export': 'Export',
    'leads.reset': 'Сбросить',
    'leads.status': 'Тип',
    'leads.aff': 'Aff',
    'leads.box': 'Box',
    'leads.country': 'Country',
    'leads.funnel': 'Funnel',
    'leads.created_period': 'Период создания',
    'leads.sent_period': 'Период отправки',
    'leads.all_time': 'Все время',
    'leads.today': 'Сегодня',
    'leads.this_week': 'Текущая неделя',
    'leads.last_7_days': 'Последние 7 дней',
    'leads.last_month': 'Последний месяц',
    'leads.this_year': 'Текущий год',
    'leads.custom': 'Ручной выбор',
    'leads.all': 'Все',
    'leads.created_date_range': 'Диапазон дат создания',
    'leads.sent_date_range': 'Диапазон дат отправки',
    'leads.from': 'От',
    'leads.to': 'До',
    'leads.displayed_columns': 'Отображаемые колонки',
    'leads.clear_all_filters': 'Очистить все фильтры',
    'leads.lead_details': 'Детали лида',
    'leads.send_history': 'История отправки',
    'leads.parameters': 'Параметры',
    'leads.send_attempts': 'Попытки отправки',
    'leads.attempt_success': 'Успешно',
    'leads.attempt_failed': 'Неудачно',
    'leads.attempt_pending': 'В ожидании',
    'leads.lead_id': 'Лид',
    'leads.created': 'Создан:',
    'leads.sent_to_broker': 'Отправлен брокеру:',
    'leads.type': 'Тип:',
    'leads.broker_status': 'Статус брокера:',
    'leads.broker': 'Брокер:',
    'leads.name': 'Имя:',
    'leads.email': 'Email:',
    'leads.phone': 'Телефон:',
    'leads.ip': 'IP:',
    'leads.country': 'Country:',
    'leads.aff': 'Aff:',
    'leads.box': 'Box (bx):',
    'leads.funnel': 'Funnel:',
    'leads.external_id': 'External ID:',
    'leads.autologin': 'Autologin:',
    'leads.broker_response': 'Ответ брокера:',
    'leads.utm': 'UTM:',
    'leads.attrs': 'Attrs:',
    'leads.clone': 'Клонировать',
    'leads.comment': 'Комментарий',
    'leads.save': 'Сохранить',
    'leads.send_attempts': 'Попытки отправки',
    'leads.when': 'Когда',
    'leads.broker_name': 'Брокер',
    'leads.attempt_number': '#',
    'leads.status': 'Статус',
    'leads.code': 'Код',
    'leads.time_ms': 'Время, мс',
    'leads.raw': 'Raw',
    'leads.not_sent': '—',
    'leads.failed': 'FAILED',
    'leads.no_attempts': 'Пока нет попыток',
    'leads.full_server_response': 'Полный ответ сервера',
    'leads.date': 'Дата',
    'leads.attempt': 'Попытка',
    'leads.response_code': 'Код ответа',
    'leads.execution_time': 'Время выполнения',
    'leads.ms': 'мс',
    'leads.no_data': 'Нет данных',
    'leads.selected': 'Выбрано',
    'leads.reset_selection': 'Сбросить',
    'leads.send': 'Отправить',
    'leads.send_tooltip': 'Некоторые лиды уже отправлены. Используйте \'Клонировать\' для повторной отправки.',
    'leads.date': 'Дата',
    'leads.sent': 'Отправлено',
    'leads.url': 'URL',
    'leads.displayed_columns': 'Отображение колонок',
    'leads.hidden_columns': 'Скрытые',
    'leads.delete_confirm': 'Удалить {count} лид(ов)?',
    'leads.delete_success': 'Удалено {count} лид(ов)',
    'leads.delete_error': 'Ошибка удаления лидов',
    'leads.clone_confirm': 'Клонировать {count} лид(ов)?',
    'leads.clone_success': 'Клонировано {count} лид(ов)',
    'leads.clone_error': 'Ошибка клонирования лидов',
    'leads.delete_confirm_title': 'Удалить лиды',
    'leads.clone_confirm_title': 'Клонировать лиды',
    
    // Статусбар
    'statusbar.success': 'Успешно',
    'statusbar.error': 'Ошибка',
    'statusbar.sending': 'Отправляется',
    'statusbar.waiting': 'Ожидание',
    'statusbar.skipped': 'Пропущен',
    'statusbar.no_active_sends': 'Нет активных отправок',
    'statusbar.unknown': 'Неизвестно',
    'statusbar.confirm_cancel': 'Вы действительно хотите отменить отправку этого лида?',
    'statusbar.cancel': 'Отменить',
    'statusbar.remove': 'Удалить',
    'statusbar.next_action': 'Следующее действие',
    'statusbar.cancel_all': 'Отменить всё',
    'statusbar.clear': 'Очистить',
    'statusbar.rejected_by_broker': 'Отклонён брокером',
    'statusbar.timeout': 'Таймаут',
    'statusbar.network_error': 'Ошибка сети',
    'statusbar.invalid_response': 'Неверный ответ',
    
    // Пользователи
    'users.search_placeholder': 'Search by name or email...',
    'users.all_roles': 'All Roles',
    'users.user': 'ПОЛЬЗОВАТЕЛЬ',
    'users.role': 'РОЛЬ',
    'users.status': 'СТАТУС',
    'users.statistics': 'СТАТИСТИКА',
    'users.api_key': 'API КЛЮЧ',
    'users.actions': 'ДЕЙСТВИЯ',
    'users.created': 'Создан:',
    'users.leads_count': 'Лидов:',
    'users.children_count': 'Детей:',
    'users.affiliate': 'Аффилиат',
    'users.affiliate_master': 'Аффилиат Мастер',
    'users.admin': 'Админ',
    'users.superadmin': 'Суперадмин',
    'users.active': 'Активен',
    'users.inactive': 'Неактивен',
    'users.edit': 'Редактировать',
    'users.delete': 'Удалить',
    'users.filter_all_roles': 'Все роли',
    'users.edit_user': 'Редактировать пользователя',
    'users.create_user': 'Создать пользователя',
    'users.name': 'Имя',
    'users.create': 'Создать',
    'users.loading': 'Загрузка пользователей...',
    'users.affiliate': 'Аффилиат',
    'users.affiliate_master': 'Мастер аффилиат',
    'users.admin': 'Администратор',
    'users.superadmin': 'Суперадмин',
    'users.role': 'Роль',
    'users.language': 'Язык',
    'users.timezone': 'Часовой пояс',
    'users.role_placeholder': 'Выберите роль',
    'users.language_placeholder': 'Выберите язык',
    'users.timezone_placeholder': 'Выберите часовой пояс',
    'users.load_error': 'Ошибка загрузки',
    'users.load_error_message': 'Не удалось загрузить пользователей',
    'users.create_success': 'Пользователь создан успешно',
    'users.create_error': 'Ошибка создания пользователя',
    'users.update_success': 'Пользователь обновлен успешно',
    'users.update_error': 'Ошибка обновления пользователя',
    'users.delete_success': 'Пользователь удален успешно',
    'users.delete_error': 'Ошибка удаления пользователя',
    'users.delete_confirm_title': 'Удалить пользователя',
    'users.delete_confirm_message': 'Вы уверены, что хотите удалить пользователя {name}?',
    'users.api_key_success': 'API ключ обновлен успешно',
    'users.api_key_error': 'Ошибка обновления API ключа',
    'users.regenerate_api_key_title': 'Сгенерировать новый API ключ',
    'users.regenerate_api_key_message': 'Вы уверены, что хотите сгенерировать новый API ключ для {name}?',
    'users.password': 'Пароль',
    'users.password_placeholder': 'Введите пароль',
    'users.generate_password': 'Сгенерировать пароль',
    'users.copy_password': 'Копировать пароль',
    'users.password_copied': 'Пароль скопирован в буфер обмена',
    'users.email_invalid': 'Введите корректный email адрес',
    'users.password_required': 'Пароль обязателен',
    'users.name_required': 'Имя обязательно',
    'users.permissions': 'Права доступа',
    'users.can_view_brokers': 'Видеть брокеров/интеграции',
    'users.can_view_boxes': 'Видеть боксы',
    'users.can_view_users': 'Видеть пользователей',
    'users.can_view_full_email': 'Показывать полный email',
    'users.can_view_full_phone': 'Показывать полный телефон',
    'users.can_resend_leads': 'Переотправлять лиды',
  },
  en: {
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.next': 'Next',
    'common.back': 'Back',
    'common.select': 'Select',
    'common.close': 'Close',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.leads': 'Leads',
    'nav.boxes': 'Boxes',
    'nav.brokers': 'Integrations',
    'nav.users': 'Users',
    'nav.settings': 'Settings',
    
    // Settings
    'settings.title': 'CRM Settings',
    'settings.timezone': 'Timezone',
    'settings.timezone.description': 'Select timezone for displaying time in CRM and working with lead delivery schedules.',
    'settings.theme': 'Color Scheme',
    'settings.theme.description': 'Select interface color scheme.',
    'settings.language': 'Interface Language',
    'settings.language.description': 'Select interface language.',
    'settings.save': 'Save Settings',
    'settings.saving': 'Saving...',
    'settings.saved': 'Settings saved',
    'settings.delivery_time_note': 'Delivery time will be calculated based on this timezone',
    'settings.current_time': 'Current time:',
    'common.updating': 'Updating...',
    
    // Themes
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.auto': 'Auto',
    
    // Users
    'users.title': 'Users',
    'users.create': 'Create User',
    'users.edit': 'Edit User',
    'users.delete': 'Delete User',
    'users.regenerate_key': 'Generate New API Key',
    'users.email': 'Email',
    'users.name': 'Name',
    'users.role': 'Role',
    'users.status': 'Status',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.leads_count': 'Leads',
    'users.children_count': 'Children',
    'users.api_key': 'API Key',
    'users.created_at': 'Created',
    'users.search_placeholder': 'Search by name or email...',
    'users.filter_all_roles': 'All Roles',
    'users.role.affiliate': 'Affiliate',
    'users.role.affiliate_master': 'Affiliate Master',
    'users.role.admin': 'Admin',
    'users.role.superadmin': 'Superadmin',
    'users.parent': 'Parent User',
    'users.no_parent': 'No Parent',
    
    // Leads
    'leads.title': 'Leads',
    'leads.create': 'Create Lead',
    'leads.edit': 'Edit Lead',
    'leads.delete': 'Delete Lead',
    'leads.name': 'Name',
    'leads.phone': 'Phone',
    'leads.email': 'Email',
    'leads.country': 'Country',
    'leads.affiliate': 'Affiliate',
    'leads.box': 'Box',
    'leads.broker': 'Broker',
    'leads.status': 'Status',
    'leads.created_at': 'Created',
    'leads.updated_at': 'Updated',
    'leads.actions': 'Actions',
    'leads.send_attempts': 'Send Attempts',
    'leads.attempt': 'Attempt',
    'leads.attempt_date': 'Attempt Date',
    'leads.attempt_status': 'Status',
    'leads.attempt_error': 'Error',
    'leads.attempt_success': 'Success',
    'leads.attempt_failed': 'Failed',
    'leads.attempt_pending': 'Pending',
    'leads.showing': 'Showing',
    'leads.of': 'of',
    'leads.total': 'total',
    'common.load_more': 'Load More',
    
    // Boxes
    'boxes.title': 'Boxes (Shipping Plans)',
    'boxes.create': 'Add Box',
    'boxes.edit': 'Edit Box',
    'boxes.delete': 'Delete Box',
    'boxes.name': 'Name',
    'boxes.description': 'Description',
    'boxes.is_active': 'Active',
    'boxes.brokers_count': 'Brokers',
    'boxes.leads_count': 'Leads',
    'boxes.description_text': 'Boxes define the priority of sending leads to brokers',
    'boxes.new_box': 'New Box',
    'boxes.countries': 'Countries',
    'boxes.countries_placeholder': 'Select countries or leave empty for all',
    'boxes.countries_hint': 'If no countries are selected, the box will be universal for all countries',
    'boxes.brokers': 'Brokers (priority 1 = highest)',
    'boxes.brokers_instruction': 'Add brokers with priorities',
    'boxes.add_broker': '+ Add Broker',
    'boxes.no_boxes': 'No boxes yet',
    'boxes.name_placeholder': 'Example: EU Premium',
    'boxes.countries_all': 'All countries',
    'boxes.countries_label': 'Countries:',
    'boxes.description_text': 'Boxes determine the priority of sending leads to brokers',
    'boxes.updated_successfully': 'Box updated!',
    'boxes.created_successfully': 'Box created!',
    'boxes.confirm_delete': 'Delete box?',
    'boxes.select_broker': 'Select broker',
    'boxes.delivery_time': 'Delivered',
    'boxes.lead_cap': 'Lead cap:',
    'boxes.lead_cap_unlimited': '∞',
    'boxes.lead_cap_hint': '(empty = no limit)',
    'boxes.from': 'from',
    'boxes.to': 'to',
    'boxes.deleted_successfully': 'Box deleted successfully',
    'boxes.save_error': 'Error saving box',
    'boxes.delete_error': 'Error deleting box',
    'boxes.delete_confirm_title': 'Delete Box',
    'boxes.max_brokers_error': 'Maximum 10 brokers per box',
    'boxes.edit': 'Edit',
    'boxes.delete': 'Delete',
    'boxes.delivery_plan': 'Delivery Plan:',
    'common.error': 'Error',
    'common.adding': 'Adding...',
    'common.back': 'Back',
    'leads.all_leads': 'All Leads',
    'brokers.update_integration': 'Update',
    'brokers.save_integration': 'Save',
    'brokers.edit': 'Edit',
    'brokers.delete': 'Delete',
    'brokers.add_parameter': '+ Add parameter',
    'brokers.no_integrations': 'No integrations created',
    'brokers.unknown_template': 'Unknown template',
    'brokers.no_active_brokers': 'No active brokers',
    'brokers.template': 'Template',
    'brokers.name_example': 'Example: Trackbox NIK',
    'brokers.manual_integration': 'Manual Integration',
    'brokers.created_successfully': 'Integration created successfully',
    'brokers.updated_successfully': 'Integration updated successfully',
    'brokers.deleted_successfully': 'Integration deleted successfully',
    'brokers.create_error': 'Error creating integration',
    'brokers.update_error': 'Error updating integration',
    'brokers.delete_error': 'Error deleting integration',
    'brokers.delete_confirm_title': 'Delete Integration',
    'brokers.delete_confirm': 'Are you sure you want to delete this integration?',
    'brokers.manual_integration_not_implemented': 'Manual integration will be implemented later',
    
    // Integrations
    'brokers.title': 'Integrations',
    'brokers.create': 'Create Integration',
    'brokers.edit': 'Edit',
    'brokers.delete': 'Delete',
    'brokers.name': 'Name',
    'brokers.code': 'Code',
    'brokers.method': 'Request Method',
    'brokers.url': 'URL',
    'brokers.headers': 'Headers',
    'brokers.body': 'Request Body',
    'brokers.is_active': 'Active',
    'brokers.method.get': 'GET',
    'brokers.method.post': 'POST',
    'brokers.method.put': 'PUT',
    'brokers.method.patch': 'PATCH',
    'brokers.method.delete': 'DELETE',
    'brokers.available_macros': 'Available Macros:',
    'brokers.macro.firstName': 'First Name',
    'brokers.macro.lastName': 'Last Name',
    'brokers.macro.email': 'Email',
    'brokers.macro.phone': 'Phone (full)',
    'brokers.macro.phonePrefix': 'Country code (auto-detection)',
    'brokers.macro.phoneNumber': 'Number without country code',
    'brokers.macro.password': 'Password (auto-generated Aa12345!)',
    'brokers.macro.country': 'Country',
    'brokers.macro.aff': 'Affiliate',
    'brokers.macro.bx': 'Box',
    'brokers.macro.funnel': 'Funnel',
    'brokers.macro.ip': 'IP Address',
    'brokers.macro.lang': 'Language',
    'brokers.macro.url': 'URL',
    'brokers.macro.clickid': 'Click ID',
    'brokers.name_placeholder': 'Example: Trackbox NIK',
    'brokers.url_placeholder': 'https://example.com/api/endpoint',
    'brokers.url_hint_get': 'For GET all parameters are specified directly in URL',
    'brokers.url_hint_post': 'URL for sending request',
    'brokers.integration_parameters': 'Integration Parameters',
    'brokers.parameters_description': 'These parameters can be used in URL, Headers and Body via macros, for example: ${partnerId}',
    'brokers.password_generation_settings': 'Password Generation Settings',
    'brokers.password_settings_description': 'Settings are used when generating the ${password} macro',
    'brokers.password_length': 'Password Length',
    'brokers.uppercase_letters': 'Uppercase letters (A-Z)',
    'brokers.lowercase_letters': 'Lowercase letters (a-z)',
    'brokers.digits': 'Digits (0-9)',
    'brokers.special_chars': 'Special characters',
    'brokers.which_special_chars': 'Which special characters to use',
    'brokers.enable_pull_api': 'Enable Pull API (receiving statuses from broker)',
    'brokers.pull_url': 'Pull URL',
    'brokers.pull_interval': 'Polling interval (minutes)',
    'brokers.pull_interval_description': 'How often to request updates (5-1440 min)',
    'brokers.pull_headers': 'Pull Headers (JSON)',
    'brokers.pull_body': 'Pull Body (JSON)',
    'brokers.pull_macros': 'Available macros: ${from} and ${to} for dates',
    'brokers.pull_info': 'Pull API',
    'brokers.pull_info_description': 'The system will automatically request lead status updates from the broker at the specified interval. Received statuses (DEPOSITOR, FTD, etc.) will be updated in CRM automatically.',
    
    // Leads
    'leads.title': 'Leads',
    'leads.search_placeholder': 'Q Search',
    'leads.filters': 'Filters',
    'leads.columns': 'Columns',
    'leads.available_fields': 'Available Fields',
    'leads.in_use': 'In Use',
    'leads.search_by_field': 'Search by Field...',
    'leads.export': 'Export',
    'leads.reset': 'Reset',
    'leads.status': 'Type',
    'leads.aff': 'Aff',
    'leads.box': 'Box',
    'leads.country': 'Country',
    'leads.funnel': 'Funnel',
    'leads.created_period': 'Creation Period',
    'leads.sent_period': 'Submission Period',
    'leads.all_time': 'All time',
    'leads.today': 'Today',
    'leads.this_week': 'This week',
    'leads.last_7_days': 'Last 7 days',
    'leads.last_month': 'Last month',
    'leads.this_year': 'This year',
    'leads.custom': 'Custom',
    'leads.all': 'All',
    'leads.created_date_range': 'Creation date range',
    'leads.sent_date_range': 'Submission date range',
    'leads.from': 'From',
    'leads.to': 'To',
    'leads.displayed_columns': 'Displayed columns',
    'leads.clear_all_filters': 'Clear all filters',
    'leads.lead_details': 'Lead Details',
    'leads.send_history': 'Send History',
    'leads.parameters': 'Parameters',
    'leads.send_attempts': 'Send Attempts',
    'leads.attempt_success': 'Success',
    'leads.attempt_failed': 'Failed',
    'leads.attempt_pending': 'Pending',
    'leads.lead_id': 'Lead',
    'leads.created': 'Created:',
    'leads.sent_to_broker': 'Sent to broker:',
    'leads.type': 'Type:',
    'leads.broker_status': 'Broker status:',
    'leads.broker': 'Broker:',
    'leads.name': 'Name:',
    'leads.email': 'Email:',
    'leads.phone': 'Phone:',
    'leads.ip': 'IP:',
    'leads.country': 'Country:',
    'leads.aff': 'Aff:',
    'leads.box': 'Box (bx):',
    'leads.funnel': 'Funnel:',
    'leads.external_id': 'External ID:',
    'leads.autologin': 'Autologin:',
    'leads.broker_response': 'Broker response:',
    'leads.utm': 'UTM:',
    'leads.attrs': 'Attrs:',
    'leads.clone': 'Clone',
    'leads.comment': 'Comment',
    'leads.save': 'Save',
    'leads.send_attempts': 'Send Attempts',
    'leads.when': 'When',
    'leads.broker_name': 'Broker',
    'leads.attempt_number': '#',
    'leads.status': 'Status',
    'leads.code': 'Code',
    'leads.time_ms': 'Time, ms',
    'leads.raw': 'Raw',
    'leads.not_sent': '—',
    'leads.failed': 'FAILED',
    'leads.no_attempts': 'No attempts yet',
    'leads.full_server_response': 'Full Server Response',
    'leads.date': 'Date',
    'leads.attempt': 'Attempt',
    'leads.response_code': 'Response Code',
    'leads.execution_time': 'Execution Time',
    'leads.ms': 'ms',
    'leads.no_data': 'No data',
    'leads.selected': 'Selected',
    'leads.reset_selection': 'Reset',
    'leads.send': 'Send',
    'leads.send_tooltip': 'Some leads are already sent. Use \'Clone\' for resending.',
    'leads.date': 'Date',
    'leads.sent': 'Sent',
    'leads.url': 'URL',
    'leads.displayed_columns': 'Display Columns',
    'leads.hidden_columns': 'Hidden',
    'leads.delete_confirm': 'Delete {count} lead(s)?',
    'leads.delete_success': 'Deleted {count} lead(s)',
    'leads.delete_error': 'Error deleting leads',
    'leads.clone_confirm': 'Clone {count} lead(s)?',
    'leads.clone_success': 'Cloned {count} lead(s)',
    'leads.clone_error': 'Error cloning leads',
    'leads.delete_confirm_title': 'Delete Leads',
    'leads.clone_confirm_title': 'Clone Leads',
    
    // Status Bar
    'statusbar.success': 'Success',
    'statusbar.error': 'Error',
    'statusbar.sending': 'Sending',
    'statusbar.waiting': 'Waiting',
    'statusbar.skipped': 'Skipped',
    'statusbar.no_active_sends': 'No active sends',
    'statusbar.unknown': 'Unknown',
    'statusbar.confirm_cancel': 'Are you sure you want to cancel sending this lead?',
    'statusbar.cancel': 'Cancel',
    'statusbar.remove': 'Remove',
    'statusbar.next_action': 'Next action',
    'statusbar.cancel_all': 'Cancel all',
    'statusbar.clear': 'Clear',
    'statusbar.rejected_by_broker': 'Rejected by broker',
    'statusbar.timeout': 'Timeout',
    'statusbar.network_error': 'Network error',
    'statusbar.invalid_response': 'Invalid response',
    
    // Users
    'users.search_placeholder': 'Search by name or email...',
    'users.all_roles': 'All Roles',
    'users.user': 'USER',
    'users.role': 'ROLE',
    'users.status': 'STATUS',
    'users.statistics': 'STATISTICS',
    'users.api_key': 'API KEY',
    'users.actions': 'ACTIONS',
    'users.created': 'Created:',
    'users.leads_count': 'Leads:',
    'users.children_count': 'Children:',
    'users.affiliate': 'Affiliate',
    'users.affiliate_master': 'Affiliate Master',
    'users.admin': 'Admin',
    'users.superadmin': 'Superadmin',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.edit': 'Edit',
    'users.delete': 'Delete',
    'users.filter_all_roles': 'All roles',
    'users.edit_user': 'Edit user',
    'users.create_user': 'Create user',
    'users.name': 'Name',
    'users.create': 'Create',
    'users.loading': 'Loading users...',
    'users.affiliate': 'Affiliate',
    'users.affiliate_master': 'Affiliate Master',
    'users.admin': 'Admin',
    'users.superadmin': 'Superadmin',
    'users.role': 'Role',
    'users.language': 'Language',
    'users.timezone': 'Timezone',
    'users.role_placeholder': 'Select role',
    'users.language_placeholder': 'Select language',
    'users.timezone_placeholder': 'Select timezone',
    'users.load_error': 'Load Error',
    'users.load_error_message': 'Failed to load users',
    'users.create_success': 'User created successfully',
    'users.create_error': 'Error creating user',
    'users.update_success': 'User updated successfully',
    'users.update_error': 'Error updating user',
    'users.delete_success': 'User deleted successfully',
    'users.delete_error': 'Error deleting user',
    'users.delete_confirm_title': 'Delete User',
    'users.delete_confirm_message': 'Are you sure you want to delete user {name}?',
    'users.api_key_success': 'API key updated successfully',
    'users.api_key_error': 'Error updating API key',
    'users.regenerate_api_key_title': 'Generate New API Key',
    'users.regenerate_api_key_message': 'Are you sure you want to generate a new API key for {name}?',
    'users.password': 'Password',
    'users.password_placeholder': 'Enter password',
    'users.generate_password': 'Generate password',
    'users.copy_password': 'Copy password',
    'users.password_copied': 'Password copied to clipboard',
    'users.email_invalid': 'Please enter a valid email address',
    'users.password_required': 'Password is required',
    'users.name_required': 'Name is required',
    'users.permissions': 'Access Rights',
    'users.can_view_brokers': 'View brokers/integrations',
    'users.can_view_boxes': 'View boxes',
    'users.can_view_users': 'View users',
    'users.can_view_full_email': 'Show full email',
    'users.can_view_full_phone': 'Show full phone',
    'users.can_resend_leads': 'Resend leads',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  // Загружаем сохраненный язык при инициализации
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['ru', 'en'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    } else {
      // Устанавливаем язык по умолчанию если сохраненный язык невалиден
      setLanguage('en');
    }
  }, []);

  // Сохраняем язык при изменении
  const handleSetLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  // Функция перевода
  const t = (key: string, params?: Record<string, string>): string => {
    const currentTranslations = translations[language];
    if (!currentTranslations) {
      console.warn(`No translations found for language: ${language}`);
      return key;
    }
    let translation = currentTranslations[key as keyof typeof currentTranslations] || key;
    
    // Заменяем параметры в переводе
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(`{${paramKey}}`, paramValue);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
